# Generated by Django 3.2.4 on 2021-08-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_or_atc', '0002_studycenter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycenter',
            name='district',
            field=models.CharField(choices=[('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasargod', 'Kasargod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thrissur', 'Thrissur'), ('Thiruvananthapuram', 'Thiruvananthapuram')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
