# Generated by Django 3.2.4 on 2021-08-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_or_atc', '0003_studycenter_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycenter',
            name='district',
            field=models.CharField(choices=[('Select District', 'Select District'), ('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasargod', 'Kasargod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thrissur', 'Thrissur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Wayanad', 'Wayanad')], max_length=50),
        ),
    ]
