# Generated by Django 3.2.4 on 2021-08-30 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_answerkey_resource'),
        ('college_or_atc', '0005_collegeaddingstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeaddingstudents',
            name='selected_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
