# Generated by Django 3.2.4 on 2021-08-30 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college_or_atc', '0006_collegeaddingstudents_selected_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeaddingstudents',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='collegeaddingstudents',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
