# Generated by Django 3.2.4 on 2021-09-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_or_atc', '0007_auto_20210830_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeaddingstudents',
            name='contact_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
