# Generated by Django 3.2.4 on 2021-08-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_answerkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerkey',
            name='assignment',
        ),
        migrations.AddField(
            model_name='answerkey',
            name='course_section',
            field=models.CharField(default='Microsoft Word', max_length=300),
            preserve_default=False,
        ),
    ]
