# Generated by Django 3.2.4 on 2021-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210824_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerkey',
            name='resource',
            field=models.CharField(max_length=400),
        ),
    ]
