# Generated by Django 3.2.4 on 2021-10-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_answerkey_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='correct_ans',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='opt1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='opt2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='opt3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='opt4',
            field=models.CharField(max_length=200),
        ),
    ]
