# Generated by Django 3.2.4 on 2021-08-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadded',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
